# Anonymize the logstore CSV
Moodle provided data from a course, the original data that Moodle provided was not completely anonymized. Therefore this notebook has been created for anonymization. This can not be reproduced, since the original logstore file has been deleted after creating an anonymous one, for privacy protection.

In [4]:
import pandas as pd

df = pd.read_csv("./log/mdl_logstore_standard_log.csv") # the original logstore, now deleted.

In the original dataset, "other" contains meta data, e.g. forum posts, where ppl introduce themselves with full name, job and city. So we replace "other" with default empty object "{}" or keep "N;".

In [7]:
df["other_m"] = df["other"]=="N;"
df["other_m"] = df["other_m"].replace({True: "N;", False: "{}"})
df["other"] = df["other_m"]
df.drop("other_m", axis=1, inplace=True)
df

,username,id,eventname,component,action,target,objecttable,objectid,crud,edulevel,...,contextlevel,contextinstanceid,courseid,anonymous,other,timecreated,origin,ip,relatedusername,realusername
0,user8540069828419911681,25017,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1417771086,web,0.0.0.0,NaN,NaN
1,user6442803380426375169,37433,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1417859881,web,0.0.0.0,NaN,NaN
2,user8540069828419911681,70090,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1418071759,web,0.0.0.0,NaN,NaN
3,user6442803380426375169,85705,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1418158739,web,0.0.0.0,NaN,NaN
4,user6442803380426375169,127065,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,2,2,0,N;,1418499579,web,0.0.0.0,NaN,NaN
5,user2882394166283730945,182480,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1418875866,web,0.0.0.0,NaN,NaN
6,user1148332538209501185,272409,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1419689198,web,0.0.0.0,NaN,NaN
7,user2882394166283730945,353391,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1420586589,web,0.0.0.0,NaN,NaN
8,user8472060408562188289,388743,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1420772915,web,0.0.0.0,NaN,NaN
9,user6442803380426375169,396553,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1420804149,web,0.0.0.0,NaN,NaN
10,user658630967098867713,419290,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1420864505,web,0.0.0.0,NaN,NaN
11,user6442803380426375169,422226,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1420888120,web,0.0.0.0,NaN,NaN
12,user805341054155882497,463458,\core\event\course_viewed,core,viewed,course,NaN,NaN,r,2,...,50,5282,5282,0,N;,1420996523,web,0.0.0.0,NaN,NaN

In [9]:
df.to_csv("log/logstore_standard_log_anonymized.csv", index=False)